final dummyWeatherJsonResponse = {
  "location": {
    "name": "London",
    "region": "City of London, Greater London",
    "country": "United Kingdom",
    "lat": 51.52,
    "lon": -0.11,
    "tz_id": "Europe/London",
    "localtime_epoch": 1721065808,
    "localtime": "2024-07-15 18:50"
  },
  "current": {
    "last_updated_epoch": 1721065500,
    "last_updated": "2024-07-15 18:45",
    "temp_c": 21.1,
    "temp_f": 70.0,
    "is_day": 1,
    "condition": {
      "text": "Light rain",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
      "code": 1183
    },
    "wind_mph": 6.9,
    "wind_kph": 11.2,
    "wind_degree": 140,
    "wind_dir": "SE",
    "pressure_mb": 1004.0,
    "pressure_in": 29.65,
    "precip_mm": 0.17,
    "precip_in": 0.01,
    "humidity": 64,
    "cloud": 75,
    "feelslike_c": 21.1,
    "feelslike_f": 70.0,
    "windchill_c": 17.0,
    "windchill_f": 62.7,
    "heatindex_c": 17.0,
    "heatindex_f": 62.7,
    "dewpoint_c": 15.9,
    "dewpoint_f": 60.6,
    "vis_km": 10.0,
    "vis_miles": 6.0,
    "uv": 4.0,
    "gust_mph": 9.5,
    "gust_kph": 15.3
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2024-07-30",
        "date_epoch": 1722297600,
        "day": {
          "maxtemp_c": 27.6,
          "maxtemp_f": 81.7,
          "mintemp_c": 23.6,
          "mintemp_f": 74.5,
          "avgtemp_c": 25.2,
          "avgtemp_f": 77.4,
          "maxwind_mph": 11.0,
          "maxwind_kph": 17.6,
          "totalprecip_mm": 4.1,
          "totalprecip_in": 0.16,
          "avgvis_km": 9.4,
          "avgvis_miles": 5.0,
          "avghumidity": 84.0,
          "condition": {
            "text": "Moderate or heavy rain shower",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/356.png",
            "code": 1243
          },
          "uv": 6.0
        },
        "astro": {
          "sunrise": "06:41 AM",
          "sunset": "07:02 PM",
          "moonrise": "01:59 AM",
          "moonset": "02:47 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": 30
        },
        "hour": [
          {
            "time_epoch": 1722294000,
            "time": "2024-07-30 00:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 6.0,
            "wind_kph": 9.7,
            "wind_degree": 245,
            "wind_dir": "WSW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.96,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 90,
            "cloud": 67,
            "feelslike_c": 26.4,
            "feelslike_f": 79.5,
            "windchill_c": 24.1,
            "windchill_f": 75.4,
            "heatindex_c": 26.4,
            "heatindex_f": 79.5,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 1,
            "chance_of_rain": 85,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 8.7,
            "vis_miles": 5.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 0.0
          },
          {
            "time_epoch": 1722297600,
            "time": "2024-07-30 01:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 6.0,
            "wind_kph": 9.7,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 90,
            "cloud": 70,
            "feelslike_c": 26.4,
            "feelslike_f": 79.5,
            "windchill_c": 24.0,
            "windchill_f": 75.2,
            "heatindex_c": 26.4,
            "heatindex_f": 79.5,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 1,
            "chance_of_rain": 72,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 0.0
          },
          {
            "time_epoch": 1722301200,
            "time": "2024-07-30 02:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 250,
            "wind_dir": "WSW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.94,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 91,
            "cloud": 73,
            "feelslike_c": 26.3,
            "feelslike_f": 79.3,
            "windchill_c": 23.9,
            "windchill_f": 75.0,
            "heatindex_c": 26.3,
            "heatindex_f": 79.3,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 1,
            "chance_of_rain": 73,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.2,
            "vis_miles": 5.0,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 0.0
          },
          {
            "time_epoch": 1722304800,
            "time": "2024-07-30 03:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 252,
            "wind_dir": "WSW",
            "pressure_mb": 1013.0,
            "pressure_in": 29.93,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 91,
            "cloud": 77,
            "feelslike_c": 26.2,
            "feelslike_f": 79.2,
            "windchill_c": 23.8,
            "windchill_f": 74.8,
            "heatindex_c": 26.2,
            "heatindex_f": 79.2,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72.0,
            "will_it_rain": 1,
            "chance_of_rain": 83,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.5,
            "vis_miles": 5.0,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 0.0
          },
          {
            "time_epoch": 1722308400,
            "time": "2024-07-30 04:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 6.0,
            "wind_kph": 9.7,
            "wind_degree": 255,
            "wind_dir": "WSW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.93,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 91,
            "cloud": 76,
            "feelslike_c": 26.1,
            "feelslike_f": 79.0,
            "windchill_c": 23.8,
            "windchill_f": 74.8,
            "heatindex_c": 26.1,
            "heatindex_f": 79.0,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72.0,
            "will_it_rain": 0,
            "chance_of_rain": 65,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.2,
            "vis_miles": 5.0,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 0.0
          },
          {
            "time_epoch": 1722312000,
            "time": "2024-07-30 05:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 257,
            "wind_dir": "WSW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.94,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 91,
            "cloud": 74,
            "feelslike_c": 26.1,
            "feelslike_f": 79.0,
            "windchill_c": 23.7,
            "windchill_f": 74.7,
            "heatindex_c": 26.1,
            "heatindex_f": 79.0,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 1,
            "chance_of_rain": 85,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.0,
            "vis_miles": 5.0,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 0.0
          },
          {
            "time_epoch": 1722315600,
            "time": "2024-07-30 06:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 259,
            "wind_dir": "W",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 91,
            "cloud": 75,
            "feelslike_c": 26.0,
            "feelslike_f": 78.8,
            "windchill_c": 23.6,
            "windchill_f": 74.5,
            "heatindex_c": 26.0,
            "heatindex_f": 78.8,
            "dewpoint_c": 22.0,
            "dewpoint_f": 71.6,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 8.7,
            "vis_miles": 5.0,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 0.0
          },
          {
            "time_epoch": 1722319200,
            "time": "2024-07-30 07:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 260,
            "wind_dir": "W",
            "pressure_mb": 1015.0,
            "pressure_in": 29.96,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 88,
            "cloud": 76,
            "feelslike_c": 26.6,
            "feelslike_f": 79.9,
            "windchill_c": 24.3,
            "windchill_f": 75.7,
            "heatindex_c": 26.6,
            "heatindex_f": 79.9,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 0,
            "chance_of_rain": 61,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 8.9,
            "vis_miles": 5.0,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 0.0
          },
          {
            "time_epoch": 1722322800,
            "time": "2024-07-30 08:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 258,
            "wind_dir": "WSW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 85,
            "cloud": 75,
            "feelslike_c": 27.4,
            "feelslike_f": 81.3,
            "windchill_c": 25.0,
            "windchill_f": 77.0,
            "heatindex_c": 27.4,
            "heatindex_f": 81.3,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 0,
            "chance_of_rain": 63,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.6,
            "vis_miles": 5.0,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 0.0
          },
          {
            "time_epoch": 1722326400,
            "time": "2024-07-30 09:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 256,
            "wind_dir": "WSW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.98,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 81,
            "cloud": 76,
            "feelslike_c": 28.2,
            "feelslike_f": 82.8,
            "windchill_c": 25.7,
            "windchill_f": 78.3,
            "heatindex_c": 28.2,
            "heatindex_f": 82.8,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72.0,
            "will_it_rain": 1,
            "chance_of_rain": 81,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.7,
            "vis_miles": 6.0,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 0.0
          },
          {
            "time_epoch": 1722330000,
            "time": "2024-07-30 10:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 79,
            "cloud": 82,
            "feelslike_c": 28.7,
            "feelslike_f": 83.7,
            "windchill_c": 26.1,
            "windchill_f": 79.0,
            "heatindex_c": 28.7,
            "heatindex_f": 83.7,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 1,
            "chance_of_rain": 83,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.4,
            "vis_miles": 5.0,
            "gust_mph": 12.1,
            "gust_kph": 19.4,
            "uv": 0.0
          },
          {
            "time_epoch": 1722333600,
            "time": "2024-07-30 11:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 240,
            "wind_dir": "WSW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.96,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 76,
            "cloud": 81,
            "feelslike_c": 29.6,
            "feelslike_f": 85.3,
            "windchill_c": 26.8,
            "windchill_f": 80.2,
            "heatindex_c": 29.6,
            "heatindex_f": 85.3,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.3,
            "will_it_rain": 1,
            "chance_of_rain": 84,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.2,
            "vis_miles": 5.0,
            "gust_mph": 12.8,
            "gust_kph": 20.5,
            "uv": 0.0
          },
          {
            "time_epoch": 1722337200,
            "time": "2024-07-30 12:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 8.7,
            "wind_kph": 14.0,
            "wind_degree": 234,
            "wind_dir": "SW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 74,
            "cloud": 82,
            "feelslike_c": 30.3,
            "feelslike_f": 86.5,
            "windchill_c": 27.3,
            "windchill_f": 81.1,
            "heatindex_c": 30.3,
            "heatindex_f": 86.5,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.3,
            "will_it_rain": 1,
            "chance_of_rain": 78,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 8.9,
            "vis_miles": 5.0,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 0.0
          },
          {
            "time_epoch": 1722340800,
            "time": "2024-07-30 13:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Moderate rain at times",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/299.png",
              "code": 1186
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 231,
            "wind_dir": "SW",
            "pressure_mb": 1013.0,
            "pressure_in": 29.93,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 74,
            "cloud": 77,
            "feelslike_c": 30.0,
            "feelslike_f": 86.0,
            "windchill_c": 27.1,
            "windchill_f": 80.8,
            "heatindex_c": 30.0,
            "heatindex_f": 86.0,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.3,
            "will_it_rain": 0,
            "chance_of_rain": 63,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.1,
            "vis_miles": 5.0,
            "gust_mph": 14.8,
            "gust_kph": 23.8,
            "uv": 0.0
          },
          {
            "time_epoch": 1722344400,
            "time": "2024-07-30 14:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 228,
            "wind_dir": "SW",
            "pressure_mb": 1013.0,
            "pressure_in": 29.91,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 74,
            "cloud": 72,
            "feelslike_c": 30.1,
            "feelslike_f": 86.2,
            "windchill_c": 27.2,
            "windchill_f": 81.0,
            "heatindex_c": 30.1,
            "heatindex_f": 86.2,
            "dewpoint_c": 22.5,
            "dewpoint_f": 72.5,
            "will_it_rain": 0,
            "chance_of_rain": 69,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.4,
            "vis_miles": 5.0,
            "gust_mph": 15.9,
            "gust_kph": 25.6,
            "uv": 0.0
          },
          {
            "time_epoch": 1722348000,
            "time": "2024-07-30 15:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Moderate rain at times",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/299.png",
              "code": 1186
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 226,
            "wind_dir": "SW",
            "pressure_mb": 1012.0,
            "pressure_in": 29.88,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 74,
            "cloud": 59,
            "feelslike_c": 30.0,
            "feelslike_f": 86.0,
            "windchill_c": 27.2,
            "windchill_f": 81.0,
            "heatindex_c": 30.0,
            "heatindex_f": 86.0,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 0,
            "chance_of_rain": 65,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.6,
            "vis_miles": 5.0,
            "gust_mph": 16.8,
            "gust_kph": 27.0,
            "uv": 0.0
          },
          {
            "time_epoch": 1722351600,
            "time": "2024-07-30 16:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 228,
            "wind_dir": "SW",
            "pressure_mb": 1012.0,
            "pressure_in": 29.89,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 76,
            "cloud": 64,
            "feelslike_c": 29.5,
            "feelslike_f": 85.1,
            "windchill_c": 26.8,
            "windchill_f": 80.2,
            "heatindex_c": 29.5,
            "heatindex_f": 85.1,
            "dewpoint_c": 22.3,
            "dewpoint_f": 72.1,
            "will_it_rain": 0,
            "chance_of_rain": 62,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.6,
            "vis_miles": 5.0,
            "gust_mph": 17.2,
            "gust_kph": 27.7,
            "uv": 0.0
          },
          {
            "time_epoch": 1722355200,
            "time": "2024-07-30 17:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 230,
            "wind_dir": "SW",
            "pressure_mb": 1012.0,
            "pressure_in": 29.89,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 79,
            "cloud": 59,
            "feelslike_c": 28.7,
            "feelslike_f": 83.7,
            "windchill_c": 26.1,
            "windchill_f": 79.0,
            "heatindex_c": 28.7,
            "heatindex_f": 83.7,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72.0,
            "will_it_rain": 0,
            "chance_of_rain": 63,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.5,
            "vis_miles": 5.0,
            "gust_mph": 17.2,
            "gust_kph": 27.7,
            "uv": 0.0
          },
          {
            "time_epoch": 1722358800,
            "time": "2024-07-30 18:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 233,
            "wind_dir": "SW",
            "pressure_mb": 1013.0,
            "pressure_in": 29.9,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 82,
            "cloud": 62,
            "feelslike_c": 27.8,
            "feelslike_f": 82.0,
            "windchill_c": 25.4,
            "windchill_f": 77.7,
            "heatindex_c": 27.8,
            "heatindex_f": 82.0,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 1,
            "chance_of_rain": 80,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.4,
            "vis_miles": 5.0,
            "gust_mph": 16.6,
            "gust_kph": 26.6,
            "uv": 0.0
          },
          {
            "time_epoch": 1722362400,
            "time": "2024-07-30 19:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 8.7,
            "wind_kph": 14.0,
            "wind_degree": 233,
            "wind_dir": "SW",
            "pressure_mb": 1013.0,
            "pressure_in": 29.91,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 84,
            "cloud": 56,
            "feelslike_c": 27.4,
            "feelslike_f": 81.3,
            "windchill_c": 25.0,
            "windchill_f": 77.0,
            "heatindex_c": 27.4,
            "heatindex_f": 81.3,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.6,
            "vis_miles": 5.0,
            "gust_mph": 15.9,
            "gust_kph": 25.6,
            "uv": 0.0
          },
          {
            "time_epoch": 1722366000,
            "time": "2024-07-30 20:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 232,
            "wind_dir": "SW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.93,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 85,
            "cloud": 54,
            "feelslike_c": 27.1,
            "feelslike_f": 80.8,
            "windchill_c": 24.7,
            "windchill_f": 76.5,
            "heatindex_c": 27.1,
            "heatindex_f": 80.8,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.8,
            "vis_miles": 6.0,
            "gust_mph": 13.6,
            "gust_kph": 22.0,
            "uv": 0.0
          },
          {
            "time_epoch": 1722369600,
            "time": "2024-07-30 21:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 8.1,
            "wind_kph": 13.0,
            "wind_degree": 232,
            "wind_dir": "SW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 87,
            "cloud": 55,
            "feelslike_c": 26.8,
            "feelslike_f": 80.2,
            "windchill_c": 24.5,
            "windchill_f": 76.1,
            "heatindex_c": 26.8,
            "heatindex_f": 80.2,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 1,
            "chance_of_rain": 73,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.9,
            "vis_miles": 6.0,
            "gust_mph": 13.6,
            "gust_kph": 22.0,
            "uv": 0.0
          },
          {
            "time_epoch": 1722373200,
            "time": "2024-07-30 22:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 234,
            "wind_dir": "SW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 87,
            "cloud": 60,
            "feelslike_c": 26.7,
            "feelslike_f": 80.1,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 26.7,
            "heatindex_f": 80.1,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 1,
            "chance_of_rain": 74,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.9,
            "vis_miles": 6.0,
            "gust_mph": 12.8,
            "gust_kph": 20.5,
            "uv": 0.0
          },
          {
            "time_epoch": 1722376800,
            "time": "2024-07-30 23:00",
            "temp_c": 25.2,
            "temp_f": 77.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 236,
            "wind_dir": "WSW",
            "pressure_mb": 1014.0,
            "pressure_in": 29.96,
            "precip_mm": 4.1,
            "precip_in": 0.16,
            "humidity": 88,
            "cloud": 60,
            "feelslike_c": 26.6,
            "feelslike_f": 79.9,
            "windchill_c": 24.3,
            "windchill_f": 75.7,
            "heatindex_c": 26.6,
            "heatindex_f": 79.9,
            "dewpoint_c": 22.1,
            "dewpoint_f": 71.8,
            "will_it_rain": 0,
            "chance_of_rain": 63,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9.9,
            "vis_miles": 6.0,
            "gust_mph": 12.1,
            "gust_kph": 19.4,
            "uv": 0.0
          }
        ]
      }
    ]
  }
};

final dummySuggestions = [
  {
    "id": 2801268,
    "name": "London",
    "region": "City of London, Greater London",
    "country": "United Kingdom",
    "lat": 51.52,
    "lon": -0.11,
    "url": "london-city-of-london-greater-london-united-kingdom"
  },
  {
    "id": 315398,
    "name": "London",
    "region": "Ontario",
    "country": "Canada",
    "lat": 42.98,
    "lon": -81.25,
    "url": "london-ontario-canada"
  },
  {
    "id": 2610925,
    "name": "Londonderry",
    "region": "New Hampshire",
    "country": "United States of America",
    "lat": 42.87,
    "lon": -71.37,
    "url": "londonderry-new-hampshire-united-states-of-america"
  }
];
